spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/felixdeploy
    username: felixdeploy
    password: FelixDeploy1234
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 9000